config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, :controllers => { :registrations => "users/registrations" }

   root 'welcome#index'

   resources :events
   resources :news
   resources :vendors
   resources :comingsoon

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       @user ||= User.new # guest user (not logged in)
        @user.roles.each { |role| send(role) }

        if @user.roles.size == 0
            can :read, :all #for guest without roles
        end
       
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end

       def admin
        can :manage, :all? 
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  before_create :set_default_role
  ROLES = %w[admin vendor author banned]

def is?(role)
  roles.include?(role.to_s)
end

def role?(base_role)
  ROLES.index(base_role.to_s) <= ROLES.index(role)
end

private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comingsoon_controller.rb
class ComingsoonController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.create event_params
    redirect_to root_path
  end

  def edit
    @event = Event.find params[:id]
  end

  def update
    @event = Event.find params[:id]
    @event.update_attributes event_params
    redirect_to root_path
  end

  def show
    @event = Event.find params[:id]
  end

  def destroy
    @event = Event.find params[:id]
    @event.delete
    redirect_to root_path
  end




private
  def event_params
    params.require(:event).permit(:name, :time, :address, :description, :latitude, :longitude)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news = News.new
  end

  def index
    @news = News.all
  end

  def create
    @news = News.create news_params
    redirect_to root_path
  end

  def edit
    @news = News.find params[:id]
  end

  def update
    @news = News.find params[:id]
    @news.update_attributes news_params
    redirect_to root_path
  end

  def show
    @news = News.find params[:id]
  end

  def destroy
    @news = News.find params[:id]
    @news.delete
    redirect_to root_path
  end

  private
  def news_params
    params.require(:news).permit(:headline, :story)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication
 
  def check_permissions
    authorize! :create, resource
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  
  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.create vendor_params
    redirect_to root_path
  end

  def edit
    @vendor = Vendor.find params[:id]
  end

  def update
    @vendor = Vendor.find params[:id]
    @vendor.update_attributes vendor_params
    redirect_to root_path
  end

  def show
    @vendor = Vendor.find params[:id]
  end

  def destroy
    @vendor = Vendor.find params[:id]
    @vendor.delete
    redirect_to root_path
  end





private
  def vendor_params
    params.require(:vendor).permit(:name, :booth, :category, :bio)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   
  def index
    @events = Event.all
    @news = News.all
    @vendors = Vendor.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

    def user_login_links
    if user_signed_in?
      link_to "Log Out", destroy_user_session_path, method: :delete
    else
      link_to "Log In", new_user_session_path
    end
  end
end

app/helpers/comingsoon_helper.rb
module ComingsoonHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comingsoon/index.html.erb
     <body style="background-image:url(assets/captain-america-throwing-his-shield.png)">
     <center>COMING SOON TRUE BELIEVERS!!!!!!!!!!!!</center>
     <p><a class="btn btn-danger btn-lg" href="/"role="button">HOME</a></p>

       <li>
                    <a href="#">Contact</a>
                <li>
                    <%= link_to "Create an Event", new_event_path %>
                    <br>
                    <% @events.each do |event| %>
                     <%= link_to event.name, event_path(event) %>
                     <%= link_to "Edit", edit_event_path(event) %>
                     <%= link_to "Delete", event_path(event), method: :delete %>
                    <br>
                    <% end %>
                    <%= link_to "Add a Vendor", new_vendor_path %>
                    <br>
                    <% @vendors.each do |vendor| %>
                      <%= link_to vendor.name, vendor_path(vendor) %>
                      <%= link_to "Edit", edit_vendor_path(vendor) %>
                      <%= link_to "Delete", vendor_path(vendor), method: :delete %>
                    <% end %>
                    <br>
                    <%= link_to "Create the News", new_news_path %>
                    <br>
                    <% @news.each do |news| %>
                      <%= link_to news.headline, news_path(news) %>
                      <%= link_to "Edit", edit_news_path(news) %>
                      <%= link_to "Delete", news_path(news), method: :delete %>
                    <br>
                    <% end %>

                <li>
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
   </body>

app/views/events/edit.html.erb
<h1>Edit that event boi</h1>

<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :time %>
  <%= f.text_field :time %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :longitude %>
  <%= f.text_area :longitude %>
  <br>
  <%= f.label :latitude %>
  <%= f.text_area :latitude %>
  <br>
  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
 <div id="wrapper" class="toggled">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/"><img src="http://www.captainscomicexpo.com/images/expo_logo.png" border="2" style="border:2px solid black;max-width:100%;" alt="CCEXPO2015" />
</a>
                         
                    
                </li>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <li>
                    <a href="/news">News</a>
                </li>
                <li>
                    <a href="/vendors">Vendors/Artists</a>
                </li>
                <li>
                    <a href="/events">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                <li>
                
                  

                <li>
                    <a href= "#" class="btn btn-danger"%>Sign Out</a>
                </li>
            </ul>
        </div>
        <a href="#menu-toggle" class="btn btn-danger" id="menu-toggle" position="float"> Menu</a>



    <!-- jQuery Version 1.11.0 -->
    <script src="assets/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="assets/bootstrap.min.js"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
 <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
</head>

<body>
<center><img class="img-responsive" src="assets/eventbub.png"  width= "55%" position="float" alt="meanwhile..." /></center>
<br>
<br>
<br>
    <!-- Page Content -->
    <div class="econ">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                
            </div>
        </div>
        <!-- /.row -->

        <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="assets/drink.jpeg" width:"700" height: "300" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3>Drink n Draw</h3>
                <h4>The Bar at Omar Shriner Convention Hall</h4>
                <p>Come kick the expo off with great libations and try your hand at sketching.
                    Open to novices as well as pros!!!!</p>
                <a class="btn btn-danger" href="/events/1">View Event <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="assets/cosplay.jpeg" width:"700" height: "300">
                </a>
            </div>
            <div class="col-md-5">
                <h3>Costume Throwdown</h3>
                <h4>All expo long!!!!!</h4>
                <p>You like dressing up as your favorite comic or sci-fi characther, well let's see it. There will be three rounds of judging with chances to win the most awesome of prizes.....</p>
                <a class="btn btn-danger" href="#">View Event <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Three -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="assets/heyrocco.jpg" width:"700" height: "300">
                </a>
            </div>
            <div class="col-md-5">
                <h3>THE PARTY TO END ALL PARTIES</h3>
                <h4>aka The Food and Wine Festival is for sellouts</h4>
                <p>Food Trucks, Local Beer, Comics inspired Cocktails, Live Music with Headliner Hey Rocco</p>
                <a class="btn btn-danger" href="#">View Event <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Four -->
        <div class="row">

            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="assets/runriot.png" width:"700" height: "300" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3>RUN RIOT PANEL</h3>
                <h4>Local Boys Done Good</h4>
                <p>Hart Jeffers and Tony Mingacci introduce Run Riot Studios to the world and their first release "Soul". Be there so you can say "I saw them when...".</p>
                <a class="btn btn-danger" href="#">View Event <span class="glyphicon glyphicon-thumbs-up"></span></a>
            </div>
        </div>
        <!-- /.row -->

        <hr>


        <!-- /.row -->

        <hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Captain's Comic Expo 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    <script src="assets/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

</body>

</html>

   

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :time %>
  <%= f.text_field :time %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<br>
<br>
<br>
<div class="jumbotron">
  
  <h1><%= @event.name %></h1>
  <br/>
  <%= @event.time %>
  <br/>
  <%= @event.address %>
  <br/>
  <%= @event.description %>

              <p><a class="btn btn-danger btn-lg" href="/events" role="Event Directory">EVENTS</a></p>
     <%= image_tag "http://maps.google.com/maps/api/staticmap?size=300x400&sensor=false&markers=#{@event.latitude}%2C#{@event.longitude}" %>
</div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
<head>
  <title>CCExpo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="/assets/styles.css" media="screen" rel="stylesheet" />
 
       
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/edit.html.erb
<h1>Edit that</h1>

<%= form_for @news do |f| %>
  <%= f.label :headline %>
  <%= f.text_field :headline %>
  <br>
  <%= f.label :story %>
  <%= f.text_area :story %>
  <br>
  <%= f.submit %>
<% end %>

app/views/news/index.html.erb
    <div id="wrapper" class="toggled" >

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/"><img src="http://www.captainscomicexpo.com/images/expo_logo.png" border="2" style="border:2px solid black;max-width:100%;" alt="CCEXPO2015" />
                    </a>
<link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>         
                    
                </li>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <li>
                    <a href="/news">News</a>
                </li>
                <li>
                    <a href="/vendors">Vendors/Artists</a>
                </li>
                <li>
                    <a href="/events">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                <li>
                
                  

                <li>
                    <a href= "#" class="btn btn-danger"%>Sign Out</a>
                </li>
            </ul>
        </div>
        <a href="#menu-toggle" class="btn btn-danger" id="menu-toggle"> Menu</a>



    <!-- jQuery Version 1.11.0 -->
    <script src="assets/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="assets/bootstrap.min.js"></script>

    <div id="wrapperHeader">
      <div id="header">
      <img src="assets/BetNew.png" alt="meanwhile..." />
      </div> 
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
     <% @news.each do |news| %>
     <div class="nav-clear"></div>
     <div class="panel panel-primary">
        <div class="panel-heading"><div class="news"><%= link_to( news_index_path(@news), :method => :get) do %>
            <%= link_to news.headline, news_path(news) %>
        </div>
        </div>
            <% end %>
            <br>
            <div class="panel-body">
            <div class="news">
                <%= news.story %>
            </div> 
            </div>

        <% end %>
        

    



    
      

app/views/news/new.html.erb
<h1>News you can use</h1>

<%= form_for @news do |f| %>
  <%= f.label :headline %>
  <%= f.text_field :headline %>
  <br>
  <%= f.label :story %>
  <%= f.text_area :story %>
  <br>
  <%= f.submit %>
<% end %>

app/views/news/show.html.erb
<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/"><img src="http://www.captainscomicexpo.com/images/expo_logo.png" border="2" style="border:2px solid black;max-width:100%;" alt="CCEXPO2015" />
</a>
                         
                    
                </li>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <li>
                    <a href="/news">News</a>
                </li>
                <li>
                    <a href="/vendors">Vendors/Artists</a>
                </li>
                <li>
                    <a href="/events">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                <li>
                
                  

                <li>
                    <a href= "#" class="btn btn-danger"%>Sign Out</a>
                </li>
            </ul>
        </div>
        <a href="#menu-toggle" class="btn btn-danger" id="menu-toggle"> Menu</a>



    <!-- jQuery Version 1.11.0 -->
    <script src="assets/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="assets/bootstrap.min.js"></script>

    <div id="wrapperHeader">
      <div id="header">
      <img src="assets/floor.png" height="350" width="1000"alt="where the action is...." />
      </div> 
     </div>

app/views/vendors/index.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">


    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="keywords" content="100% grid, layout, columns, images, thumbnails, responsive, full width grid, image grid, css, jquery" />
        <link rel="shortcut icon" href="../favicon.ico">
        <link rel="stylesheet" type="text/css" href="assets/default.css" />
        <link rel="stylesheet" type="text/css" href="assets/component.css" />
        <script src="assets/modernizr.custom.js"></script>
    </head>




<div id="wrapper" class= "toggled">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/"><img src="http://www.captainscomicexpo.com/images/expo_logo.png" border="2" style="border:2px solid black;max-width:100%;" alt="CCEXPO2015" />
</a>
                         
                    
                </li>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <li>
                    <a href="/news">News</a>
                </li>
                <li>
                    <a href="/vendors">Vendors/Artists</a>
                </li>
                <li>
                    <a href="/events">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                <li>
                
                  

                <li>
                    <a href= "#" class="btn btn-danger"%>Sign Out</a>
                </li>
            </ul>
        </div>
        <a href="#menu-toggle" class="btn btn-danger" id="menu-toggle"> Menu</a>



    <!-- jQuery Version 1.11.0 -->
    <script src="assets/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="assets/bootstrap.min.js"></script>

    
      


<body>
        <div class="container" >
            <header class="clearfix">
            </header>
            <center><img class="img-responsive" src="assets/vendob.png"  width= "55%" position="float" alt="meanwhile..." /></center>
            <link href='http://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>  
            <ul class="cbp-rfgrid">
                <li><a href="/vendors/1"><img src="assets/cap.png" /><div><h3>BOOTH 100</h3></div></a></li>
                <li><a href="#"><img src="assets/3.png" /><div><h3>BOOTH 300</h3></div></a></li>
                <li><a href="#"><img src="assets/9.png" /><div><h3>BOOTH 208</h3></div></a></li>
                <li><a href="#"><img src="assets/bab.png" /><div><h3>BOOTH 420</h3></div></a></li>
                <li><a href="#"><img src="assets/y.jpg" /><div><h3>BOOTH 353</h3></div></a></li>
                <li><a href="#"><img src="assets/fine.jpg" /><div><h3>BOOTH 411</h3></div></a></li>
                <li><a href="#"><img src="assets/act.jpg" /><div><h3>BOOTH 121</h3></div></a></li>
                <li><a href="#"><img src="assets/5.jpg" /><div><h3>BOOTH 242</h3></div></a></li>
                <li><a href="#"><img src="assets/4.png" /><div><h3>BOOTH 616</h3></div></a></li>
                <li><a href="#"><img src="assets/dc.jpg" /><div><h3>BOOTH 132</h3></div></a></li>
                <li><a href="#"><img src="assets/sdd.jpg" /><div><h3>BOOTH 234</h3></div></a></li>
                <li><a href="#"><img src="assets/d.jpg" /><div><h3>BOOTH 254</h3></div></a></li>
                <li><a href="#"><img src="assets/skull.jpg" /><div><h3>BOOTH 656</h3></div></a></li>
                <li><a href="#"><img src="assets/some.jpg" /><div><h3>BOOTH 878</h3></div></a></li>
                <li><a href="#"><img src="assets/7.png" /><div><h3>BOOTH 555</h3></div></a></li>
                <li><a href="#"><img src="assets/val.jpg" /><div><h3>BOOTH 777</h3></div></a></li>
                <li><a href="#"><img src="assets/marvel.jpg" /><div><h3>BOOTH 616</h3></div></a></li>
                <li><a href="#"><img src="assets/drew.jpg" /><div><h3>BOOTH 222</h3></div></a></li>
                <li><a href="#"><img src="assets/dragon.jpg" /><div><h3>BOOTH 522</h3></div></a></li>
                <li><a href="#"><img src="assets/l.jpg" /><div><h3>BOOTH 222</h3></div></a></li>
                <li><a href="#"><img src="assets/stan.jpg" /><div><h3>BOOTH 777</h3></div></a></li>
                <li><a href="#"><img src="assets/max.jpg" /><div><h3>BOOTH 333</h3></div></a></li>
                <li><a href="#"><img src="assets/x.jpg" /><div><h3>BOOTH 788</h3></div></a></li>
                <li><a href="#"><img src="assets/game.jpg" /><div><h3>BOOTH 242</h3></div></a></li>
                <li><a href="#"><img src="assets/goor.jpg" /><div><h3>BOOTH 266</h3></div></a></li>
                <li><a href="#"><img src="assets/hero.jpg" /><div><h3>BOOTH 888</h3></div></a></li>
                <li><a href="#"><img src="assets/sdd.jpg" /><div><h3>BOOTH 433</h3></div></a></li>
                <li><a href="#"><img src="assets/topshelf.jpg" /><div><h3>BOOTH 333</h3></div></a></li>
                <li><a href="#"><img src="assets/val.jpg" /><div><h3>BOOTH 111</h3></div></a></li>
                <li><a href="#"><img src="assets/w.jpg" /><div><h3>BOOTH 666</h3></div></a></li>
            </ul>
        </div>
        <center><img class="img-responsive" src="assets/floor.png"  width= "90%" position="float" alt="meanwhile..." /></center>
   




<div class = "vt">
     <table>
        <thead>
        <th>VENDORS</th>
        </thead>
        <tbody>
            <tr>
            <% @vendors.each do |vendor| %>
            <%= link_to vendor.name, vendor_path(vendor) %>
            <br>
            <%= vendor.booth %>
            <br>
            <%= vendor.category %>
            <br>
            <br>
            </tr>
        </tbody>
            <br>

        <% end %>
     </div>
    </body>
</html>